id: class_info
title: 职业信息
text: |-
  {{#if state.tempClass == 'warrior'}}
  战士是埃尔德拉世界中最常见的战斗职业，精通各种武器和防具的使用。他们通过严格的训练和实战经验锻炼出强健的体魄和出色的战斗技巧。
  
  战士可以担任前线防御者或强力输出者的角色，保护队友免受敌人的攻击，或者直接消灭威胁。在城市卫队、贵族护卫和冒险者公会中，战士都是不可或缺的存在。
  
  作为战士，你将获得以下属性修正：
  • 力量: +2
  • 智力: +0
  • 魅力: +0
  • 幸运: +0
  
  起始技能：
  • 防御姿态 - 提高防御力，降低受到的伤害
  • 猛力一击 - 对敌人造成更高的伤害
  {{/if}}
  
  {{#if state.tempClass == 'mage'}}
  法师是魔法艺术的专家，通过对元素、能量和其他神秘力量的研究和操控，施展强大的法术。他们的力量来源于知识和对奥术的深入理解。
  
  法师可以通过法术造成大范围伤害，或者提供各种有用的辅助效果。在学术界和皇家顾问中，有才能的法师备受尊敬，许多人终生致力于魔法的研究。
  
  作为法师，你将获得以下属性修正：
  • 力量: -1
  • 智力: +3
  • 魅力: +0
  • 幸运: +0
  
  起始技能：
  • 火球术 - 向敌人投掷一个火球，造成伤害
  • 魔法护盾 - 创造一个保护自己的魔法屏障
  {{/if}}
  
  {{#if state.tempClass == 'ranger'}}
  游侠是荒野的守护者，精通追踪、狩猎和远程武器的使用。他们与自然有着密切的联系，能够在最恶劣的环境中生存。
  
  游侠可以通过弓箭等远程武器造成伤害，同时具备较高的机动性。他们常作为向导、猎人和侦察兵，在未开发地区的探索中发挥关键作用。
  
  作为游侠，你将获得以下属性修正：
  • 力量: +1
  • 智力: +1
  • 魅力: +0
  • 幸运: +1
  
  起始技能：
  • 精准射击 - 使用弓箭造成高额伤害
  • 野外生存 - 在野外更容易找到食物和资源
  {{/if}}
  
  {{#if state.tempClass == 'rogue'}}
  盗贼是隐秘行动的大师，擅长潜行、解锁和发现隐藏的宝藏。他们依靠敏捷、智慧和一套特殊工具来完成任务。
  
  盗贼可以通过突袭造成高额伤害，或者通过潜行避开危险。在城市中，盗贼可能是小偷、间谍或密探；在冒险队伍中，他们负责解除陷阱和开启锁着的宝箱。
  
  作为盗贼，你将获得以下属性修正：
  • 力量: +0
  • 智力: +1
  • 魅力: +1
  • 幸运: +2
  
  起始技能：
  • 背刺 - 从背后攻击敌人，造成额外伤害
  • 开锁 - 更容易打开锁着的门和箱子
  {{/if}}
image: {{state.tempClass}}.jpg
choices:
  - id: confirm_class
    text: 选择这个职业
    target: character_creation
    effect: |-
      if(!state.character) state.character = {};
      state.character.class = state.tempClass;
      delete state.tempClass;
  
  - id: back_to_classes
    text: 返回职业选择
    target: class_selection