id: race_info
title: 种族信息
text: |-
  {{#if state.tempRace == 'human'}}
  人类是埃尔德拉世界中最为常见和适应性最强的种族。他们生命短暂但充满活力，能够在各种环境中生存和繁衍。
  
  人类社会多样且充满变化，从繁华的城市到偏远的村庄，他们建立了各种形式的文明。人类对知识和进步的渴望使他们成为优秀的学者、工匠和冒险家。
  
  作为人类，你将获得以下属性修正：
  • 力量: +1
  • 智力: +1
  • 魅力: +1
  • 幸运: +1
  
  特殊能力：适应性 - 人类学习新技能的速度比其他种族更快。
  {{/if}}
  
  {{#if state.tempRace == 'elf'}}
  精灵是埃尔德拉最古老的种族之一，以其优雅的外表和长寿而闻名。他们与自然有着深厚的联系，通常居住在茂密的森林中。
  
  精灵社会重视艺术、魔法和知识的传承。他们精通弓箭和魔法，是出色的法师和游侠。精灵对其他种族保持一定距离，但在面对共同威胁时会伸出援手。
  
  作为精灵，你将获得以下属性修正：
  • 力量: +0
  • 智力: +2
  • 魅力: +1
  • 幸运: +1
  
  特殊能力：夜视 - 精灵在黑暗中也能看清物体。
  {{/if}}
  
  {{#if state.tempRace == 'dwarf'}}
  矮人是坚韧强壮的种族，通常居住在山脉深处。他们以精湛的锻造技艺和坚固的防御工事而闻名。
  
  矮人社会注重传统、家族和荣誉。他们是出色的工匠、铁匠和战士，创造的武器和盔甲质量上乘。矮人性格固执，但对朋友忠诚无比。
  
  作为矮人，你将获得以下属性修正：
  • 力量: +2
  • 智力: +0
  • 魅力: +0
  • 幸运: +2
  
  特殊能力：坚韧不拔 - 矮人对毒素和疾病有更强的抵抗力。
  {{/if}}
  
  {{#if state.tempRace == 'orc'}}
  兽人是强大而好战的种族，生活在部落社会中。他们崇尚力量和战斗技巧，部落领袖通常是最强大的战士。
  
  兽人社会以部落为单位，重视个体的力量和为部落做出的贡献。尽管常被其他种族视为野蛮人，但兽人有着丰富的口头传统和深厚的荣誉感。
  
  作为兽人，你将获得以下属性修正：
  • 力量: +3
  • 智力: -1
  • 魅力: +0
  • 幸运: +0
  
  特殊能力：战斗狂热 - 兽人在战斗中能够进入狂暴状态，提高攻击力。
  {{/if}}
image: {{state.tempRace}}.jpg
choices:
  - id: confirm_race
    text: 选择这个种族
    target: character_creation
    effect: |-
      if(!state.character) state.character = {};
      state.character.race = state.tempRace;
      delete state.tempRace;
  
  - id: back_to_races
    text: 返回种族选择
    target: race_selection